### ISSUE TITLE
unicode error: UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 15: invalid start byte

### ISSUE THREAD

**Issue by lcorsini** [ozzieperez/packtpub-library-downloader#21]
when downloading I've encountered this error (python 2.7 on windows)

```
Traceback (most recent call last):
  File "downloader.py", line 374, in <module>
    main(sys.argv[1:])
  File "downloader.py", line 332, in main
    download_book(book, books_directory, book_assets, session, headers)
  File "downloader.py", line 101, in download_book
    print(title.encode(sys.stdout.encoding, errors='replace').decode())
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa9 in position 15: invalid start byte
```
There is a way to see what is the book that causes this error?

**Comment by lcorsini** [comment]
well it seems easy, I actually replaced the line
`print(title.encode(sys.stdout.encoding, errors='replace').decode())`
with:
`print(title.encode(sys.stdout.encoding, errors='ignore').decode('unicode_escape').encode('utf-8'))`

the culprit was the registered mark character (the book was:
Learning Unreal® Engine iOS Game Development)
