### ISSUE TITLE
Doesn't work, cannot log in

### ISSUE THREAD

**Issue by acealchemycyberblaze** [ozzieperez/packtpub-library-downloader#43]
Attempting to login...                                                                                                                     
Traceback (most recent call last):                                                                                                          
File "downloader.py", line 377, in <module>                                                                                                  
main(sys.argv[1:])                                                                                                                       
File "downloader.py", line 293, in main                                                                                                      
form_build_id = tree.xpath('//form[@id="packt-user-login-form"]//input[@name="form_build_id"]/@id')[0]                                 IndexError: list index out of range

**Comment by Sadaananth** [comment]
I am also getting the same error. any luck?
